### ISSUE TITLE
Meaning of data list in excel sheet

### ISSUE THREAD

**Issue by zhanhang123** [MariaLavrovskaya/LGD-predictions#1]
I am very interested in your project, but have some questions,  I've been looking at the data for a long time, but I can't find the meaning of each column of data, can you tell me. Thank you.

**Comment by MariaLavrovskaya** [comment]
Morning. Happy to hear that you find my project interesting. Apologies for not specifying it in the ReadME file, this is sorted now. The meaning of every column can be found in here: http://www.freddiemac.com/fmac-resources/research/pdf/user_guide.pdf

**Comment by zhanhang123** [comment]
Hi, I'm very glad you can answer my question. Best wishes for you.
